-- The commerce schema (orders, order_items, order_events, snacks_public) is a
-- migration now: supabase/migrations/20261005080000_commerce.sql. It is applied
-- with the other migrations (docs/SELF-HOSTING.md §2) and checked by
-- supabase/tests/rls-smoke.sql. This file stays so old links still resolve;
-- there is nothing to run here.
